require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  EnabledByDefault: true
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.6
  Exclude: [vendor/**/*]
Rails: { Enabled: true }

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - describe
    - exec
    - exit
    - gem
    - include
    - load
    - puts
    - rails_require
    - require
    - require_relative
    - ruby
    - source
    - to
    - warn
  IncludedMacros:
    - system!
  Exclude:
    - 'config.ru'
    - 'config/boot.rb'
    - 'config/puma.rb'
Style/MixinUsage: { Exclude: ['bin/**/*'] }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/schema.rb'
  AutoCorrect: true

################################################################################
#
# Rules we don't want to enable
#
################################################################################

Bundler/GemComment: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DocumentationMethod: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/MissingElse: { Enabled: false }
