require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  EnabledByDefault: true
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.6
  Exclude: [node_modules/**/*, vendor/**/*]
Rails: { Enabled: true }

Metrics/BlockLength:
  Exclude:
    - Guardfile
Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - default
    - describe
    - exec
    - exit
    - gem
    - include
    - it
    - layout
    - load
    - not_to
    - puts
    - rails_require
    - require
    - require_relative
    - ruby
    - source
    - to
    - validates
    - warn
  IgnoreMacros: false
  Exclude:
    - bin/**/*
    - 'config.ru'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - db/**/*.rb
    - Guardfile
    - Gemfile
Style/MixinUsage: { Exclude: ['bin/**/*'] }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/schema.rb'
  AutoCorrect: true

################################################################################
#
# Rules we don't want to enable
#
################################################################################

Bundler/GemComment: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/Documentation: { Enabled: false }
Style/DocumentationMethod: { Enabled: false }
Style/InlineComment: { Enabled: false }
Style/MissingElse: { Enabled: false }
Style/StringHashKeys: { Enabled: false }
