default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: yourappnamehere_development

test:
  <<: *default
  database: yourappnamehere_test

production:
  <<: *default
  database: yourappnamehere_production
